/* eslint-disable no-console */
import { randomBytes } from 'crypto';
import fs from 'fs-extra';
import path from 'path';
import pc from 'picocolors';
import { DataSource, DataSourceOptions } from 'typeorm';
import { MysqlDriver } from 'typeorm/driver/mysql/MysqlDriver';
import { camelCase } from 'typeorm/util/StringUtils';

import { preBootstrapConfig } from './bootstrap';
import { resetConfig } from './config/config-helpers';
import { VendureConfig } from './config/vendure-config';
import { getDatabaseType } from './connection/database-type';

/**
 * @description
 * Configuration for generating a new migration script via {@link generateMigration}.
 *
 * @docsCategory migration
 */
export interface MigrationOptions {
    /**
     * @description
     * The name of the migration. The resulting migration script will be named
     * `{TIMESTAMP}-{name}.ts`.
     */
    name: string;
    /**
     * @description
     * The output directory of the generated migration scripts.
     */
    outputDir?: string;
    /**
     * @description
     * When set to `true`, the migration is generated by diffing the entity metadata against a
     * freshly-provisioned, empty "shadow" database rather than against the configured database.
     * This produces a complete "zero to current schema" baseline migration even when the
     * configured database is already populated - useful for creating the initial migration for an
     * existing project, or regenerating a baseline in CI.
     *
     * For SQL-based databases (Postgres, MySQL/MariaDB) this creates and drops a temporary database
     * on the same server; the configured database server must be reachable (and, for Postgres, the
     * configured database must exist, since the temporary database is created from a connection to
     * it). For SQLite-based databases an in-memory database is used.
     *
     * @default false
     */
    fromEmpty?: boolean;
}

/**
 * @description
 * Runs any pending database migrations. See [TypeORM migration docs](https://typeorm.io/#/migrations)
 * for more information about the underlying migration mechanism.
 *
 * @docsCategory migration
 */
export async function runMigrations(userConfig: Partial<VendureConfig>): Promise<string[]> {
    const config = await preBootstrapConfig(userConfig);
    const connection = await createDataSource(createDataSourceOptions(config));
    const migrationsRan: string[] = [];
    try {
        const migrations = await disableForeignKeysForSqLite(connection, () =>
            connection.runMigrations({ transaction: 'each' }),
        );
        for (const migration of migrations) {
            log(pc.green(`Successfully ran migration: ${migration.name}`));
            migrationsRan.push(migration.name);
        }
    } catch (e: any) {
        log(pc.red('An error occurred when running migrations:'));
        log(e.message);
        if (isRunningFromVendureCli()) {
            throw e;
        } else {
            process.exitCode = 1;
        }
    } finally {
        await checkMigrationStatus(connection);
        await connection.destroy();
        resetConfig();
    }
    return migrationsRan;
}

async function checkMigrationStatus(connection: DataSource) {
    const builderLog = await connection.driver.createSchemaBuilder().log();
    if (builderLog.upQueries.length) {
        log(
            pc.yellow(
                'Your database schema does not match your current configuration. Generate a new migration for the following changes:',
            ),
        );
        for (const query of builderLog.upQueries) {
            log(' - ' + pc.yellow(query.query));
        }
    }
}

/**
 * @description
 * Reverts the last applied database migration. See [TypeORM migration docs](https://typeorm.io/#/migrations)
 * for more information about the underlying migration mechanism.
 *
 * @docsCategory migration
 */
export async function revertLastMigration(userConfig: Partial<VendureConfig>) {
    const config = await preBootstrapConfig(userConfig);
    const connection = await createDataSource(createDataSourceOptions(config));
    try {
        await disableForeignKeysForSqLite(connection, () =>
            connection.undoLastMigration({ transaction: 'each' }),
        );
    } catch (e: any) {
        log(pc.red('An error occurred when reverting migration:'));
        log(e.message);
        if (isRunningFromVendureCli()) {
            throw e;
        } else {
            process.exitCode = 1;
        }
    } finally {
        await connection.destroy();
        resetConfig();
    }
}

/**
 * @description
 * Generates a new migration file based on any schema changes (e.g. adding or removing CustomFields).
 * See [TypeORM migration docs](https://typeorm.io/#/migrations) for more information about the
 * underlying migration mechanism.
 *
 * @docsCategory migration
 */
export async function generateMigration(
    userConfig: Partial<VendureConfig>,
    options: MigrationOptions,
): Promise<string | undefined> {
    const config = await preBootstrapConfig(userConfig);
    const { connection, cleanup } = options.fromEmpty
        ? await createEmptyDatabaseConnection(config)
        : { connection: await createDataSource(createDataSourceOptions(config)), cleanup: undefined };

    let migrationName: string | undefined;
    try {
        // TODO: This can hopefully be simplified if/when TypeORM exposes this CLI command directly.
        // See https://github.com/typeorm/typeorm/issues/4494
        const sqlInMemory = await connection.driver.createSchemaBuilder().log();
        // mysql escapes identifiers with backticks, so its migration query strings are wrapped in
        // double quotes; every other driver uses template-literal backticks.
        const isMysql = connection.driver instanceof MysqlDriver;
        const upSqls = sqlInMemory.upQueries.map(q => formatMigrationQuery(q.query, q.parameters, isMysql));
        const downSqls = sqlInMemory.downQueries.map(q =>
            formatMigrationQuery(q.query, q.parameters, isMysql),
        );

        if (upSqls.length) {
            if (options.name) {
                const timestamp = new Date().getTime();
                const filename = timestamp.toString() + '-' + options.name + '.ts';
                const directory = options.outputDir;
                const fileContent = getTemplate(options.name as any, timestamp, upSqls, downSqls.reverse());
                const outputPath = directory
                    ? path.join(directory, filename)
                    : path.join(process.cwd(), filename);
                await fs.ensureFile(outputPath);
                fs.writeFileSync(outputPath, fileContent);

                log(pc.green(`Migration ${pc.blue(outputPath)} has been generated successfully.`));
                migrationName = outputPath;
            }
        } else {
            log(pc.yellow('No changes in database schema were found - cannot generate a migration.'));
        }
    } finally {
        // Nested so that a failing connection.destroy() still drops the shadow database (cleanup)
        // and resets the config, rather than orphaning the shadow DB and leaking the admin
        // connection.
        try {
            await connection.destroy();
        } finally {
            if (cleanup) {
                await cleanup();
            }
            resetConfig();
        }
    }
    return migrationName;
}

function createDataSourceOptions(userConfig: Partial<VendureConfig>): DataSourceOptions {
    return Object.assign({ logging: ['query', 'error', 'schema'] }, userConfig.dbConnectionOptions, {
        subscribers: [],
        synchronize: false,
        migrationsRun: false,
        dropSchema: false,
        logger: 'advanced-console',
    });
}

function createDataSource(options: DataSourceOptions): Promise<DataSource> {
    return new DataSource(options).initialize();
}

interface EmptyDatabaseConnection {
    connection: DataSource;
    /**
     * Tears down any temporary database that was provisioned. Must be called *after* the
     * {@link connection} has been destroyed.
     */
    cleanup?: () => Promise<void>;
}

/**
 * Provisions a connection to a guaranteed-empty database of the same dialect as the configured
 * database, so that {@link generateMigration} can diff the entity metadata against a blank schema
 * and produce a complete "zero to current" baseline migration.
 *
 * For server-based databases a temporary "shadow" database is created on the same server and
 * dropped again via the returned `cleanup` callback (the Prisma/Atlas approach). For SQLite-based
 * databases an in-memory database is used, which needs no cleanup.
 */
async function createEmptyDatabaseConnection(
    config: Partial<VendureConfig>,
): Promise<EmptyDatabaseConnection> {
    const baseOptions = createDataSourceOptions(config);
    switch (getDatabaseType(baseOptions)) {
        // aurora-postgres/aurora-mysql are intentionally excluded: they connect over the Aurora
        // Data API, where `CREATE DATABASE` is not supported the same way, and this has not been
        // verified - so they fall through to the clear "unsupported" error below.
        case 'postgres':
            return provisionShadowDatabase(baseOptions, 'postgres');
        case 'mysql':
        case 'mariadb':
            return provisionShadowDatabase(baseOptions, 'mysql');
        case 'better-sqlite3':
        case 'sqlite':
        case 'sqljs':
            return { connection: await createDataSource(emptySqliteOptions(baseOptions)) };
        default:
            throw new Error(
                `Generating a migration from an empty database is not supported for the "${baseOptions.type}" ` +
                    'driver. Supported drivers: postgres, mysql, mariadb, better-sqlite3, sqlite, sql.js.',
            );
    }
}

/**
 * Builds a shadow database name suffix that is unique across concurrent processes: the pid
 * distinguishes separate `vendure migrate` runs against the same server (e.g. a CI matrix or shared
 * staging DB), while the timestamp, counter and random chunk keep it unique within a process even
 * when two are provisioned in the same millisecond.
 */
let shadowDatabaseCounter = 0;
function uniqueShadowSuffix(): string {
    const random = randomBytes(3).toString('hex');
    return `${process.pid}_${Date.now()}_${shadowDatabaseCounter++}_${random}`;
}

/**
 * Replicated setups (`replication.master`/`replication.slaves`) source the connection - including
 * the database - from the replica config rather than the top-level options. Flatten to the master
 * so a shadow/admin connection targets a single, writable node.
 */
export function flattenReplication(options: DataSourceOptions): DataSourceOptions {
    const replication = (options as any).replication;
    if (!replication?.master) {
        return options;
    }
    const { replication: _replication, ...rest } = options as any;
    return { ...rest, ...replication.master } as DataSourceOptions;
}

/**
 * Points connection options at a specific database. A database embedded in a connection `url`
 * overrides the top-level `database`, so the url's path is rewritten to match.
 */
export function withDatabase(options: DataSourceOptions, database: string): DataSourceOptions {
    const next = { ...options, database } as any;
    if (typeof next.url === 'string') {
        const url = new URL(next.url);
        url.pathname = `/${database}`;
        next.url = url.toString();
    }
    return next as DataSourceOptions;
}

async function provisionShadowDatabase(
    baseOptions: DataSourceOptions,
    dialect: 'postgres' | 'mysql',
): Promise<EmptyDatabaseConnection> {
    const shadowName = `vendure_shadow_${uniqueShadowSuffix()}`;
    const quotedName = dialect === 'postgres' ? `"${shadowName}"` : `\`${shadowName}\``;

    // Replicated setups source the connection (including the database) from replication.master;
    // flatten to the master so both connections target a single, writable node.
    const master = flattenReplication(baseOptions);

    // An admin connection to the *configured* database, used only to create and later drop the
    // temporary shadow database.
    const admin = await createDataSource({
        ...master,
        entities: [],
        migrations: [],
        logging: false,
    } as DataSourceOptions);

    // Match the configured charset for mysql so the shadow schema is built identically to the
    // real target. The charset comes from config (validated as an identifier), the name is
    // internally generated - neither is an injection surface.
    const charset = (master as any).charset;
    const charsetClause =
        dialect === 'mysql' && typeof charset === 'string' && /^\w+$/.test(charset)
            ? ` CHARACTER SET ${charset}`
            : '';

    try {
        await admin.query(`CREATE DATABASE ${quotedName}${charsetClause}`);
    } catch (e: any) {
        await admin.destroy();
        throw new Error(
            `Could not create the temporary shadow database ${shadowName}. Ensure the configured database ` +
                `user has permission to create databases. Original error: ${e.message as string}`,
        );
    }

    let connection: DataSource;
    try {
        // `withDatabase` retargets the shadow connection at shadowName, accounting for a database
        // embedded in a connection `url` (which would otherwise override the top-level `database`
        // and point the shadow connection back at the real configured database).
        connection = await createDataSource(withDatabase(master, shadowName));
    } catch (e) {
        // The shadow database was created but we could not connect to it - drop it so it is not
        // left behind, then surface the original error.
        await admin.query(`DROP DATABASE IF EXISTS ${quotedName}`).catch(() => undefined);
        await admin.destroy();
        throw e;
    }

    return {
        connection,
        cleanup: async () => {
            try {
                if (dialect === 'postgres') {
                    // Terminate any lingering backends so the DROP cannot fail with
                    // "database is being accessed by other users" (version-agnostic).
                    await admin.query(
                        'SELECT pg_terminate_backend(pid) FROM pg_stat_activity ' +
                            `WHERE datname = '${shadowName}' AND pid <> pg_backend_pid()`,
                    );
                }
                await admin.query(`DROP DATABASE IF EXISTS ${quotedName}`);
            } finally {
                await admin.destroy();
            }
        },
    };
}

function emptySqliteOptions(baseOptions: DataSourceOptions): DataSourceOptions {
    if (baseOptions.type === 'sqljs') {
        // For sqljs the database can be a Uint8Array of saved bytes; unset it (and the save
        // callback/location) so the shadow really is an empty in-memory database, not a restored
        // copy of a populated one.
        return {
            ...baseOptions,
            location: undefined,
            database: undefined,
            autoSave: false,
            autoSaveCallback: undefined,
        } as unknown as DataSourceOptions;
    }
    return { ...baseOptions, database: ':memory:' } as DataSourceOptions;
}

/**
 * There is a bug in TypeORM which causes db schema changes to fail with SQLite. This
 * is a work-around for the issue.
 * See https://github.com/typeorm/typeorm/issues/2576#issuecomment-499506647
 */
async function disableForeignKeysForSqLite<T>(connection: DataSource, work: () => Promise<T>): Promise<T> {
    const dbType = getDatabaseType(connection);
    const isSqLite = dbType === 'sqlite' || dbType === 'better-sqlite3';
    if (isSqLite) {
        await connection.query('PRAGMA foreign_keys=OFF');
    }
    const result = await work();
    if (isSqLite) {
        await connection.query('PRAGMA foreign_keys=ON');
    }
    return result;
}

/**
 * Formats a single schema-builder query as a line of migration source. mysql escapes identifiers
 * with backticks, so its queries are wrapped in double quotes; all other drivers use backticks.
 */
function formatMigrationQuery(query: string, parameters: any[] | undefined, isMysql: boolean): string {
    const quote = isMysql ? '"' : '`';
    const escaped = query.replace(new RegExp(quote, 'g'), `\\${quote}`);
    return `        await queryRunner.query(${quote}${escaped}${quote}, ${JSON.stringify(parameters)});`;
}

/**
 * Gets contents of the migration file.
 */
function getTemplate(name: string, timestamp: number, upSqls: string[], downSqls: string[]): string {
    return `import {MigrationInterface, QueryRunner} from "typeorm";

export class ${camelCase(name, true)}${timestamp} implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
${upSqls.join(`
`)}
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
${downSqls.join(`
`)}
   }

}
`;
}

function log(message: string) {
    // If running from within the Vendure CLI, we allow the CLI app
    // to handle the logging.
    if (isRunningFromVendureCli()) {
        return;
    }
    console.log(message);
}

function isRunningFromVendureCli(): boolean {
    return process.env.VENDURE_RUNNING_IN_CLI != null;
}
