/* eslint-disable no-console */
import fs from 'fs-extra';
import path from 'path';
import pc from 'picocolors';
import { Connection, createConnection, DataSourceOptions } from 'typeorm';
import { MysqlDriver } from 'typeorm/driver/mysql/MysqlDriver';
import { camelCase } from 'typeorm/util/StringUtils';

import { preBootstrapConfig } from './bootstrap';
import { resetConfig } from './config/config-helpers';
import { VendureConfig } from './config/vendure-config';

/**
 * @description
 * Configuration for generating a new migration script via {@link generateMigration}.
 *
 * @docsCategory migration
 */
export interface MigrationOptions {
    /**
     * @description
     * The name of the migration. The resulting migration script will be named
     * `{TIMESTAMP}-{name}.ts`.
     */
    name: string;
    /**
     * @description
     * The output directory of the generated migration scripts.
     */
    outputDir?: string;
    /**
     * @description
     * When set to `true`, the migration is generated by diffing the entity metadata against a
     * freshly-provisioned, empty "shadow" database rather than against the configured database.
     * This produces a complete "zero to current schema" baseline migration even when the
     * configured database is already populated - useful for creating the initial migration for a
     * new project, or in CI where no populated database is available.
     *
     * For SQL-based databases (Postgres, MySQL/MariaDB) this creates and drops a temporary
     * database on the same server. For SQLite-based databases an in-memory database is used.
     *
     * @default false
     */
    fromEmpty?: boolean;
}

/**
 * @description
 * Runs any pending database migrations. See [TypeORM migration docs](https://typeorm.io/#/migrations)
 * for more information about the underlying migration mechanism.
 *
 * @docsCategory migration
 */
export async function runMigrations(userConfig: Partial<VendureConfig>): Promise<string[]> {
    const config = await preBootstrapConfig(userConfig);
    const connection = await createConnection(createConnectionOptions(config));
    const migrationsRan: string[] = [];
    try {
        const migrations = await disableForeignKeysForSqLite(connection, () =>
            connection.runMigrations({ transaction: 'each' }),
        );
        for (const migration of migrations) {
            log(pc.green(`Successfully ran migration: ${migration.name}`));
            migrationsRan.push(migration.name);
        }
    } catch (e: any) {
        log(pc.red('An error occurred when running migrations:'));
        log(e.message);
        if (isRunningFromVendureCli()) {
            throw e;
        } else {
            process.exitCode = 1;
        }
    } finally {
        await checkMigrationStatus(connection);
        await connection.close();
        resetConfig();
    }
    return migrationsRan;
}

async function checkMigrationStatus(connection: Connection) {
    const builderLog = await connection.driver.createSchemaBuilder().log();
    if (builderLog.upQueries.length) {
        log(
            pc.yellow(
                'Your database schema does not match your current configuration. Generate a new migration for the following changes:',
            ),
        );
        for (const query of builderLog.upQueries) {
            log(' - ' + pc.yellow(query.query));
        }
    }
}

/**
 * @description
 * Reverts the last applied database migration. See [TypeORM migration docs](https://typeorm.io/#/migrations)
 * for more information about the underlying migration mechanism.
 *
 * @docsCategory migration
 */
export async function revertLastMigration(userConfig: Partial<VendureConfig>) {
    const config = await preBootstrapConfig(userConfig);
    const connection = await createConnection(createConnectionOptions(config));
    try {
        await disableForeignKeysForSqLite(connection, () =>
            connection.undoLastMigration({ transaction: 'each' }),
        );
    } catch (e: any) {
        log(pc.red('An error occurred when reverting migration:'));
        log(e.message);
        if (isRunningFromVendureCli()) {
            throw e;
        } else {
            process.exitCode = 1;
        }
    } finally {
        await connection.close();
        resetConfig();
    }
}

/**
 * @description
 * Generates a new migration file based on any schema changes (e.g. adding or removing CustomFields).
 * See [TypeORM migration docs](https://typeorm.io/#/migrations) for more information about the
 * underlying migration mechanism.
 *
 * @docsCategory migration
 */
export async function generateMigration(
    userConfig: Partial<VendureConfig>,
    options: MigrationOptions,
): Promise<string | undefined> {
    const config = await preBootstrapConfig(userConfig);
    const { connection, cleanup } = options.fromEmpty
        ? await createEmptyDatabaseConnection(config)
        : { connection: await createConnection(createConnectionOptions(config)), cleanup: undefined };

    let migrationName: string | undefined;
    try {
        // TODO: This can hopefully be simplified if/when TypeORM exposes this CLI command directly.
        // See https://github.com/typeorm/typeorm/issues/4494
        const sqlInMemory = await connection.driver.createSchemaBuilder().log();
        const upSqls: string[] = [];
        const downSqls: string[] = [];

        // mysql is exceptional here because it uses ` character in to escape names in queries, that's why for mysql
        // we are using simple quoted string instead of template string syntax
        if (connection.driver instanceof MysqlDriver) {
            sqlInMemory.upQueries.forEach(upQuery => {
                upSqls.push(
                    '        await queryRunner.query("' +
                        upQuery.query.replace(new RegExp('"', 'g'), '\\"') +
                        '", ' +
                        JSON.stringify(upQuery.parameters) +
                        ');',
                );
            });
            sqlInMemory.downQueries.forEach(downQuery => {
                downSqls.push(
                    '        await queryRunner.query("' +
                        downQuery.query.replace(new RegExp('"', 'g'), '\\"') +
                        '", ' +
                        JSON.stringify(downQuery.parameters) +
                        ');',
                );
            });
        } else {
            sqlInMemory.upQueries.forEach(upQuery => {
                upSqls.push(
                    '        await queryRunner.query(`' +
                        upQuery.query.replace(new RegExp('`', 'g'), '\\`') +
                        '`, ' +
                        JSON.stringify(upQuery.parameters) +
                        ');',
                );
            });
            sqlInMemory.downQueries.forEach(downQuery => {
                downSqls.push(
                    '        await queryRunner.query(`' +
                        downQuery.query.replace(new RegExp('`', 'g'), '\\`') +
                        '`, ' +
                        JSON.stringify(downQuery.parameters) +
                        ');',
                );
            });
        }

        if (upSqls.length) {
            if (options.name) {
                const timestamp = new Date().getTime();
                const filename = timestamp.toString() + '-' + options.name + '.ts';
                const directory = options.outputDir;
                const fileContent = getTemplate(options.name as any, timestamp, upSqls, downSqls.reverse());
                const outputPath = directory
                    ? path.join(directory, filename)
                    : path.join(process.cwd(), filename);
                await fs.ensureFile(outputPath);
                fs.writeFileSync(outputPath, fileContent);

                log(pc.green(`Migration ${pc.blue(outputPath)} has been generated successfully.`));
                migrationName = outputPath;
            }
        } else {
            log(pc.yellow('No changes in database schema were found - cannot generate a migration.'));
        }
    } finally {
        await connection.close();
        if (cleanup) {
            await cleanup();
        }
        resetConfig();
    }
    return migrationName;
}

function createConnectionOptions(userConfig: Partial<VendureConfig>): DataSourceOptions {
    return Object.assign({ logging: ['query', 'error', 'schema'] }, userConfig.dbConnectionOptions, {
        subscribers: [],
        synchronize: false,
        migrationsRun: false,
        dropSchema: false,
        logger: 'advanced-console',
    });
}

interface EmptyDatabaseConnection {
    connection: Connection;
    /**
     * Tears down any temporary database that was provisioned. Must be called *after* the
     * {@link connection} has been closed.
     */
    cleanup?: () => Promise<void>;
}

/**
 * Provisions a connection to a guaranteed-empty database of the same dialect as the configured
 * database, so that {@link generateMigration} can diff the entity metadata against a blank schema
 * and produce a complete "zero to current" baseline migration.
 *
 * For server-based databases a temporary "shadow" database is created on the same server and
 * dropped again via the returned `cleanup` callback (the Prisma/Atlas approach). For SQLite-based
 * databases an in-memory database is used, which needs no cleanup.
 */
async function createEmptyDatabaseConnection(
    config: Partial<VendureConfig>,
): Promise<EmptyDatabaseConnection> {
    const baseOptions = createConnectionOptions(config);
    switch (baseOptions.type) {
        case 'postgres':
        case 'aurora-postgres':
            return provisionShadowDatabase(baseOptions, 'postgres');
        case 'mysql':
        case 'mariadb':
        case 'aurora-mysql':
            return provisionShadowDatabase(baseOptions, 'mysql');
        case 'better-sqlite3':
        case 'sqlite':
        case 'sqljs':
            return { connection: await createConnection(emptySqliteOptions(baseOptions)) };
        default:
            throw new Error(
                `Generating a migration from an empty database is not supported for the "${baseOptions.type}" ` +
                    'driver. Supported drivers: postgres, mysql, mariadb, better-sqlite3, sqlite, sql.js.',
            );
    }
}

/**
 * A monotonically-increasing counter combined with a timestamp guarantees a unique shadow database
 * name even if two are provisioned within the same millisecond.
 */
let shadowDatabaseCounter = 0;
function uniqueShadowSuffix(): string {
    return `${Date.now()}_${shadowDatabaseCounter++}`;
}

async function provisionShadowDatabase(
    baseOptions: DataSourceOptions,
    dialect: 'postgres' | 'mysql',
): Promise<EmptyDatabaseConnection> {
    const shadowName = `vendure_shadow_${uniqueShadowSuffix()}`;
    const quotedName = dialect === 'postgres' ? `"${shadowName}"` : `\`${shadowName}\``;

    // An admin connection to the *configured* database, used only to create and later drop the
    // temporary shadow database.
    const admin = await createConnection({
        ...baseOptions,
        name: `vendure-shadow-admin-${shadowName}`,
        entities: [],
        migrations: [],
        logging: false,
    } as DataSourceOptions);

    try {
        await admin.query(`CREATE DATABASE ${quotedName}`);
    } catch (e: any) {
        await admin.close();
        throw new Error(
            `Could not create the temporary shadow database ${shadowName}. Ensure the configured database ` +
                `user has permission to create databases. Original error: ${e.message as string}`,
        );
    }

    let connection: Connection;
    try {
        connection = await createConnection({
            ...baseOptions,
            name: `vendure-shadow-${shadowName}`,
            database: shadowName,
        } as DataSourceOptions);
    } catch (e) {
        // The shadow database was created but we could not connect to it - drop it so it is not
        // left behind, then surface the original error.
        await admin.query(`DROP DATABASE IF EXISTS ${quotedName}`).catch(() => undefined);
        await admin.close();
        throw e;
    }

    return {
        connection,
        cleanup: async () => {
            try {
                if (dialect === 'postgres') {
                    // Terminate any lingering backends so the DROP cannot fail with
                    // "database is being accessed by other users" (version-agnostic).
                    await admin.query(
                        'SELECT pg_terminate_backend(pid) FROM pg_stat_activity ' +
                            `WHERE datname = '${shadowName}' AND pid <> pg_backend_pid()`,
                    );
                }
                await admin.query(`DROP DATABASE IF EXISTS ${quotedName}`);
            } finally {
                await admin.close();
            }
        },
    };
}

function emptySqliteOptions(baseOptions: DataSourceOptions): DataSourceOptions {
    const shared = {
        ...baseOptions,
        name: `vendure-shadow-${uniqueShadowSuffix()}`,
    };
    if (baseOptions.type === 'sqljs') {
        return { ...shared, location: undefined, autoSave: false } as DataSourceOptions;
    }
    return { ...shared, database: ':memory:' } as DataSourceOptions;
}

/**
 * There is a bug in TypeORM which causes db schema changes to fail with SQLite. This
 * is a work-around for the issue.
 * See https://github.com/typeorm/typeorm/issues/2576#issuecomment-499506647
 */
async function disableForeignKeysForSqLite<T>(connection: Connection, work: () => Promise<T>): Promise<T> {
    const isSqLite = connection.options.type === 'sqlite' || connection.options.type === 'better-sqlite3';
    if (isSqLite) {
        await connection.query('PRAGMA foreign_keys=OFF');
    }
    const result = await work();
    if (isSqLite) {
        await connection.query('PRAGMA foreign_keys=ON');
    }
    return result;
}

/**
 * Gets contents of the migration file.
 */
function getTemplate(name: string, timestamp: number, upSqls: string[], downSqls: string[]): string {
    return `import {MigrationInterface, QueryRunner} from "typeorm";

export class ${camelCase(name, true)}${timestamp} implements MigrationInterface {

   public async up(queryRunner: QueryRunner): Promise<any> {
${upSqls.join(`
`)}
   }

   public async down(queryRunner: QueryRunner): Promise<any> {
${downSqls.join(`
`)}
   }

}
`;
}

function log(message: string) {
    // If running from within the Vendure CLI, we allow the CLI app
    // to handle the logging.
    if (isRunningFromVendureCli()) {
        return;
    }
    console.log(message);
}

function isRunningFromVendureCli(): boolean {
    return process.env.VENDURE_RUNNING_IN_CLI != null;
}
